#!/bin/sh

#$1 cli; $2 OEM user; $3 OEM user password; $4 database; $5 dbcred; $6 hostcred; 
#$7 jobname; $8 mode; $9 level; $10 freq; $11 begin_time; $12 interval; $13 timezone;

cli=$1
if [ $8 = FULL ];
then
        if [ $9 = ALL ];
        then
                mode=full
                bak_name=fulldb
        else
                mode='incremental level 0'
                bak_name=dblevel0
        fi
elif [ $8 = DIFF ];
then
        mode="incremental level $9"
        bak_name=dblevel$9
else
        mode="incremental level $9 cumulative"
        bak_name=dblevel${9}_cum
fi

$cli logout

#$cli login -username='sysman' -password='Huawei123' >> /dev/null 
$cli login -username=${2} -password=${3} >> /dev/null
if [ $? -ne 0 ];
then
   echo "Error : login failure."
   exit 1
fi

echo "create job property_file"
cat>/tmp/backupprop.txt<<EOF
name=$7
type=RMANScript
owner=SYSMAN
target_list=$4:oracle_database
cred.defaultDBCred.<all_targets>:oracle_database=NAMED:SYSMAN:$5
cred.defaultHostCred.<all_targets>:oracle_database=NAMED:SYSMAN:$6
variable.rman_perl_script=<<MULTILINEVALUE
shutdown immediate;
startup mount;
run{
allocate channel oem_backup_disk1 type disk  maxpiecesize 1000 G;
backup
$mode
tag "$7"
format="/opt/oracle/backups/${bak_name}_t%t_s%s_p%p"
database
include current controlfile; 
release channel oem_backup_disk1;
}
shutdown immediate;
startup mount;
sql "alter database noarchivelog";
sql"alter database open";
MULTILINEVALUE
schedule.frequency=${10}
schedule.startTime=${11}
schedule.interval=${12}
schedule.timezone.region=${13}
EOF

echo "$cli create_job -name=$7 -type=RMANScript -input_file=property_file:/tmp/backupprop.txt"
$cli create_job -name=$7 -type=RMANScript -input_file=property_file:/tmp/backupprop.txt
if [ $? -ne 0 ]; 
then
   echo "Error : run backupScript failure."
   $cli logout >> /dev/null
   exit 1
fi

$cli logout >> /dev/null
if [ $? -ne 0 ];
then
   echo "Error : logout failure."
   exit 1
fi
